chore: correct config 6

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -69,11 +69,11 @@ jobs:
           exit 1
 
       - name: Generate Coverage
-        run: mix coveralls.html
+        run: mix coveralls
         id: coverage
 
-      # - name: Check Coverage
-      #   if: steps.coverage.outcome != 'success' || steps.coverage.outputs.coverage < 80
-      #   run: |
-      #     echo "Failed due to low coverage - ${{ steps.coverage.outputs.coverage }}%"
-      #     exit 1
+      - name: Check Coverage
+        if: steps.coverage.outcome != 'success' || steps.coverage.outputs.coverage < 80
+        run: |
+          echo "Failed due to low coverage - ${{ steps.coverage.outputs.coverage }}%"
+          exit 1
